all:
  children:

    masters:
      hosts:
        master:
          ansible_host: 192.168.1.20

    workers:
      hosts:
        worker1:
          ansible_host: 192.168.1.21

        worker2:
          ansible_host: 192.168.1.22
